version: "3"

services:

  node0:
    build: .
    image: my_pow_sydacoin
    ports:
        - "10000:10000"
    environment:
      PEERS: 'node1,node2'
      NAME: "alice"

  node1:
    image: my_pow_sydacoin
    ports:
        - "10001:10000"
    environment:
      PEERS: 'node0,node2'
      NAME: "bob"

  node2:
    image: my_pow_sydacoin
    ports:
        - "10002:10000"
    environment:
      PEERS: 'node0,node1'
      NAME: "joan"

