version: "3"

services:

  node0:
    build: .
    image: powcoin
    ports:
        - "10000:10000"
    environment:
      PEERS: 'node1,node2'
      HOSTNAME: "node0"
      USERNAME: "alice"

  node1:
    image: powcoin
    ports:
        - "10001:10000"
    environment:
      PEERS: 'node0'
      HOSTNAME: "node1"
      USERNAME: "bob"

  node2:
    image: powcoin
    ports:
        - "10002:10000"
    environment:
      PEERS: 'node0'
      HOSTNAME: "node2"
      USERNAME: "joan"

